### PR TITLE
Improvement of the export/import statement and the distinction between shared and static for MSVC.

### PR DESCRIPTION
**Pull request by OgreTransporter**

### CODE REVIEW

**Comment by abellgithub** [comment]
It's unclear what problem this is solving. Please open an issue with a good description.

**Comment by OgreTransporter** [comment]
It is actually not a problem, but an improvement. The control of import/export of static and shared library. Comparable with https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/zconf.h.cmakein#L337

**Comment by abellgithub** [comment]
That's not really helpful. What does it improve, exactly?

**Comment by OgreTransporter** [comment]
As it is now, it is not so easy to switch between the static and the shared library under MSVC because shared is fixed. With the changes I can compile a program like PDAL with `LAZPERF_LIB_STATIC`, then static is used. If the switch is missing, shared is used automatically. In addition, only the header `lazperf_base.hpp` has to be changed in case of a version change. The second header `lazperf_user_base.hpp` is no longer needed. Actually this file should be generated by a template and the version of CMake should be entered there, but I can still change that.

The solution for zlib is similar. If you specify `ZLIB_DLL` shared is used otherwise static. For non-MSVC users, of course, this is not an improvement.

**Comment by abellgithub** [comment]
The current licence for lazperf does not permit static linking, though we
expect this will be changed soon.

**Comment by OgreTransporter** [comment]
> The current licence for lazperf does not permit static linking, though we expect this will be changed soon.

For PDAL, this is true. However, other LGPL projects can also be linked statically.

If the license is changed anyway, then you can wait with the merge until the license change.

**Comment by hobu** [comment]
@OgreTransporter I think this entire issue has gone away for PDAL now that we've simply vendored the laz-perf code in it. Are you still wanting to merge this given that?

**Pull request closed without merging**
